# Generated by Django 3.2.8 on 2021-10-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_nit', models.CharField(max_length=12)),
                ('cus_fir_name', models.CharField(max_length=45)),
                ('cus_last_name', models.CharField(max_length=45)),
                ('cus_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('cus_email', models.CharField(blank=True, max_length=45, null=True)),
                ('cus_address', models.CharField(max_length=45)),
                ('cus_city', models.CharField(max_length=20)),
                ('cus_datetime_add', models.DateTimeField()),
                ('cus_datetime_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nit', models.CharField(max_length=12)),
                ('emp_fir_name', models.CharField(max_length=45)),
                ('emp_last_name', models.CharField(max_length=45)),
                ('emp_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_address', models.CharField(max_length=45)),
                ('emp_key', models.CharField(max_length=8)),
                ('emp_datetime_ingress', models.DateTimeField()),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nit', models.CharField(max_length=12)),
                ('prov_tradename', models.CharField(max_length=45)),
                ('prov_address', models.CharField(max_length=100)),
                ('prov_contact_fir_name', models.CharField(max_length=45)),
                ('prov_contact_last_name', models.CharField(max_length=45)),
                ('prov_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('prov_email', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_datetime_ingress', models.DateTimeField()),
            ],
            options={
                'db_table': 'provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_description', models.CharField(max_length=100)),
                ('prod_unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prod_stock', models.PositiveIntegerField()),
                ('prod_datetime_ingress', models.DateTimeField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.provider')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_address', models.CharField(max_length=45)),
                ('cus_city', models.CharField(max_length=20)),
                ('ord_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ord_datetime_order', models.DateTimeField()),
                ('ord_datetime_dispatch', models.DateTimeField()),
                ('ord_observation', models.CharField(blank=True, max_length=150, null=True)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customers')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.roles'),
        ),
        migrations.CreateModel(
            name='DetailOrders',
            fields=[
                ('dt_ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_ord_description', models.CharField(max_length=45)),
                ('dt_ord_unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dt_ord_quantity', models.PositiveIntegerField()),
                ('dt_ord_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.orders')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.products')),
            ],
            options={
                'db_table': 'detail_orders',
                'managed': True,
            },
        ),
    ]
